<script setup lang="ts">
import Qrcode from 'qrcode.vue'

const medicineId = ref<string>('')
const medicineName = ref<string>('')
const medicinePrice = ref<number>(2)
const medicineQuantity = ref<number>(100)
const isSavingOnChain = ref<boolean>(true)
const dataSavedOnChain = ref<boolean>(false)

function onSubmit() {
  dataSavedOnChain.value = true
}

onMounted(() => {
  medicineId.value = `medicine_${nanoid(10)}`
})
</script>

<template>
  <div fc class="w-1/2" mx-auto>
    <Heading title="Add Medicine" />
    <form class="w-full mx-auto mt-10" @submit.prevent="onSubmit">
      <div class="mb-4">
        <label for="name" class="block text-sm font-medium text-gray-700">Autogenerated ID</label>
        <input id="name" v-model="medicineId" disabled type="text" name="name" class="mt-1 p-2 block w-full border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm">
      </div>

      <div class="mb-4">
        <label for="name" class="block text-sm font-medium text-gray-700">Name</label>
        <input id="name" v-model="medicineName" type="text" name="name" class="mt-1 p-2 block w-full border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm">
      </div>
      <div class="mb-4">
        <label for="price" class="block text-sm font-medium text-gray-700">Price</label>
        <input id="price" v-model="medicinePrice" type="number" name="price" class="mt-1 p-2 block w-full border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm">
      </div>
      <div class="mb-4">
        <label for="quantity" class="block text-sm font-medium text-gray-700">Quantity</label>
        <input id="quantity" v-model="medicineQuantity" type="number" name="quantity" class="mt-1 p-2 block w-full border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm">
      </div>
      <button type="submit" class="w-full bg-teal-500 hover:bg-teal-700 text-white font-bold py-2 px-4 rounded" fjic w-full>
        <div v-if="!isSavingOnChain">
          Add to FLOW CHain
        </div>
        <div v-else>
          <div loading w-6 h-6 />
        </div>
      </button>

      <span class="inline-block pt-2 text-lg">(This shall add the data to FLOW Blockchain and generate a QR Code for the ID)</span>
    </form>

    <div v-if="dataSavedOnChain" mt-10 space-y-4>
      <Heading title="Generated QR Code for ID:" class="text-red-700" />
      <Qrcode :value="medicineId" class="h-70 w-auto" render-as="svg" />
    </div>
  </div>
</template>

<style scoped>

</style>
