<script setup lang="ts">
import Qrcode from 'qrcode.vue'
import * as fcl from '@onflow/fcl'
import ADD_DOCTOR_TRANSACTION from '@/cadence/transactions/doctors/addDoctor.cdc?raw'

const doctorId = ref<string>('')
const doctorName = ref<string>('')
const doctorSpecialization = ref<string>('')
const isSavingOnChain = ref<boolean>(false)
const dataSavedOnChain = ref<boolean>(false)

async function onSubmit() {
  const requestPromise = push.promise('Registering doctors to the FLOW chain database')
  const txnId = await fcl.mutate({
    cadence: ADD_DOCTOR_TRANSACTION,
    // @ts-expect-error no typings
    args: (arg, t) => [
      arg(doctorId.value, t.String),
      arg(doctorName.value, t.String),
      arg(doctorSpecialization.value, t.String),
    ],
  })

  TransactionModals.value.push({
    title: 'Storing doctor data to FLOW Chain',
    transactionId: txnId,
  })

  await fcl.tx(txnId).onceSealed()
  requestPromise.resolve('Data saved on FLOW Blockchain successfully')

  dataSavedOnChain.value = true

  doctorId.value = `doctor_${nanoid(10)}`
  doctorName.value = ''
  doctorSpecialization.value = ''
}

onMounted(() => {
  if (!isUserLoggedIn)
    navigateTo('/')

  doctorId.value = `doctor_${nanoid(10)}`
})
</script>

<template>
  <div fc class="w-1/2" mx-auto>
    <Heading title="Register Doctor" />
    <form class="w-full mx-auto mt-10" @submit.prevent="onSubmit">
      <div class="mb-4">
        <label for="doctorId" class="block text-sm font-medium text-gray-700">Autogenerated ID</label>
        <input id="doctorId" v-model="doctorId" disabled type="text" name="doctorId" class="mt-1 p-2 block w-full border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm">
      </div>

      <div class="mb-4">
        <label for="doctorName" class="block text-sm font-medium text-gray-700">Doctor Name</label>
        <input id="doctorName" v-model="doctorName" type="text" name="doctorName" class="mt-1 p-2 block w-full border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm">
      </div>
      <div class="mb-4">
        <label for="doctorSpecialization" class="block text-sm font-medium text-gray-700">Specialization</label>
        <input id="doctorSpecialization" v-model="doctorSpecialization" type="text" name="doctorSpecialization" class="mt-1 p-2 block w-full border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm">
      </div>
      <button type="submit" class="w-full bg-teal-500 hover:bg-teal-700 text-white font-bold py-2 px-4 rounded" fjic w-full>
        <div v-if="!isSavingOnChain">
          Register and Save data on FLOW chain
        </div>
        <div v-else>
          <div loading w-6 h-6 />
        </div>
      </button>

      <span class="inline-block pt-2 text-lg">(This shall add the data to FLOW Blockchain, which would enable patients to add reviews on profile)</span>
    </form>

    <div v-if="dataSavedOnChain" mt-10 space-y-4>
      <Heading title="Generated QR Code for ID:" class="text-red-700" />
      <Qrcode :value="medicineId" class="h-70 w-auto" render-as="svg" />
    </div>
  </div>
</template>

<style scoped>

</style>
