<script setup lang="ts">
import * as fcl from '@onflow/fcl'
import ADD_BILL_TRANSACTION from '~/cadence/transactions/bills/addBill.cdc?raw'

const billId = ref<string>('')
const billName = ref<string>('')
const billEmail = ref<string>('')
const billExpense = ref<string>('')
const billCost = ref<number>(10)
const isSavingOnChain = ref<boolean>(false)

async function onSubmit() {
  if (!billName.value || !billEmail.value || !billExpense.value || !billCost.value) {
    push.error('Please fill all the fields')
    return
  }

  const requestPromise = push.promise('Adding bill data to the FLOW chain database')
  const txnId = await fcl.mutate({
    cadence: ADD_BILL_TRANSACTION,
    // @ts-expect-error no typings
    args: (arg, t) => [
      arg(billId.value, t.String),
      arg(billName.value, t.String),
      arg(billEmail.value, t.String),
      arg(billExpense.value, t.String),
      arg(billCost.value, t.Int),
    ],
  })

  TransactionModals.value.push({
    title: 'Adding Bill data to FLOW Chain',
    transactionId: txnId,
  })

  await fcl.tx(txnId).onceSealed()
  requestPromise.resolve('Data saved on FLOW Blockchain successfully')

  sendMail(
    billEmail.value,
        `Bill Generated for ${billName.value}`,
        `Your bill has been generated successfully. Please find the details below:<br><br>
        Bill ID: ${billId.value}<br>
        Expense: ${billExpense.value}<br>
        Cost: ${billCost.value}<br>
        <br>
        FLOW Transaction ID: ${txnId}<br>
        FLOW Explorer: <a href="https://testnet.flowscan.org/transaction/${txnId}" target="_blank">View Transaction</a>,
        `,
  )

  billId.value = `bill_${nanoid(10)}`
  billName.value = ''
  billEmail.value = ''
  billExpense.value = ''
  billCost.value = 10
}

onMounted(() => {
  if (!isUserLoggedIn)
    navigateTo('/')

  billId.value = `bill_${nanoid(10)}`
})
</script>

<template>
  <div>
    <Heading title="Generate Bill" />

    <!-- create a form to take input from user about full name, email and contents of the medical expenses, along with name and cost, style it using tailwindcss -->
    <form class="w-full mx-auto mt-10" @submit.prevent="onSubmit">
      <div class="mb-4">
        <label for="name" class="block text-sm font-medium text-gray-700">Autogenerated ID</label>
        <input id="name" v-model="billId" disabled type="text" name="name" class="mt-1 p-2 block w-full border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm">
      </div>

      <div class="mb-4">
        <label for="name" class="block text-sm font-medium text-gray-700">Full Name</label>
        <input id="name" v-model="billName" type="text" name="name" class="mt-1 p-2 block w-full border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm">
      </div>

      <div class="mb-4">
        <label for="mail" class="block text-sm font-medium text-gray-700">Email</label>
        <input id="mail" v-model="billEmail" type="email" name="email" class="mt-1 p-2 block w-full border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm">
      </div>

      <div class="mb-4">
        <label for="billExpense" class="block text-sm font-medium text-gray-700">Expense</label>
        <input id="billExpense" v-model="billExpense" type="text" name="billExpense" class="mt-1 p-2 block w-full border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm">
      </div>
      <div class="mb-4">
        <label for="billCost" class="block text-sm font-medium text-gray-700">Cost</label>
        <input id="billCost" v-model="billCost" type="number" name="billCost" class="mt-1 p-2 block w-full border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm">
      </div>
      <button type="submit" class="w-full bg-teal-500 hover:bg-teal-700 text-white font-bold py-2 px-4 rounded" fjic w-full>
        <div v-if="!isSavingOnChain">
          Save Data on-chain & Send Bill
        </div>
        <div v-else>
          <div loading w-6 h-6 />
        </div>
      </button>

      <span class="inline-block pt-2 text-lg">(This shall add the data to FLOW Blockchain and send an email to the patient, where they can pay using FLOW tokens / NFTs)</span>
    </form>
  </div>
</template>

<style scoped>

</style>
